baseURL = 'https://4anime.pages.dev'
languageCode = 'en-us'
title = '4anime'
theme = 'anime'
enableRobotsTXT = 'true'
paginate = 18

[params]
  Description = 'Animes English Sub, Anime Online, Animes Online, Anime Streaming English Subtitle, Watch Anime Online, Watch Anime Dub, Free Anime, Animixplay, 4anime.'
  favicon = 'https://i3.wp.com/www.chineseanime.co.in/wp-content/uploads/2021/09/cropped-4865770.jpg'
  twitter = 'Rizqy'
[markup.goldmark.renderer]
 unsafe = true
[taxonomies]
  genre = 'genre'
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "genre"
    weight = 90
  [[related.indices]]
    name = "title"
    weight = 90
  [[related.indices]]
    name = "type"
    weight = 100