baseURL = 'https://4anime.pages.dev'
languageCode = 'en-us'
title = 'Batchs Pages'
theme = 'anime'
enableRobotsTXT = 'true'
paginate = 18

[params]
  Description = 'Anime Batch Sub Indo, Download Anime Batch Sub Indo, Anime Sub Indo Batch, Download Anime Sub Indo Batch, Download Batch Anime Sub Indo.'
  favicon = 'https://img.icons8.com/ios-filled/512/209cee/sharingan.png'
  twitter = 'Rizqy'
[markup.goldmark.renderer]
 unsafe = true
[taxonomies]
  genre = 'genre'
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "genre"
    weight = 90
  [[related.indices]]
    name = "title"
    weight = 90
  [[related.indices]]
    name = "type"
    weight = 100